// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFBAY_o3HOwjvG0wJB-jBK5YUX9V9XCAM',
    appId: '1:1087710383114:web:9833a4f01168ee034ae3f3',
    messagingSenderId: '1087710383114',
    projectId: 'aplikasita-bad30',
    authDomain: 'aplikasita-bad30.firebaseapp.com',
    storageBucket: 'aplikasita-bad30.appspot.com',
    measurementId: 'G-K4PD29LWKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgAfP8TVt6OYkPYx8SjOwSy12fQfRwlE8',
    appId: '1:1087710383114:android:0eae46540e065f0d4ae3f3',
    messagingSenderId: '1087710383114',
    projectId: 'aplikasita-bad30',
    storageBucket: 'aplikasita-bad30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdI83pCgLbsjWp_cwf9zuQauPhDoiMx9s',
    appId: '1:1087710383114:ios:b1c1598d543fac394ae3f3',
    messagingSenderId: '1087710383114',
    projectId: 'aplikasita-bad30',
    storageBucket: 'aplikasita-bad30.appspot.com',
    iosBundleId: 'com.example.aplikasiPengelola',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdI83pCgLbsjWp_cwf9zuQauPhDoiMx9s',
    appId: '1:1087710383114:ios:b1c1598d543fac394ae3f3',
    messagingSenderId: '1087710383114',
    projectId: 'aplikasita-bad30',
    storageBucket: 'aplikasita-bad30.appspot.com',
    iosBundleId: 'com.example.aplikasiPengelola',
  );
}
